version: '3.8'

services:
  mongodb:
    image: mongo:4.4.1
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - db-network

  postgresql:
    image: postgres:13.0
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - db-network

  neo4j:
    image: neo4j:4.1.3
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 512m
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - db-network

  redis:
    image: redis:6.0.8
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - db-network

volumes:
  mongodb_data:
  postgresql_data:
  neo4j_data:
  neo4j_logs:
  redis_data:

networks:
  db-network:
    driver: bridge
